# Generated by Django 3.2.5 on 2021-07-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NpmPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npm_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=16)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NpmPackageDependecy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npm_package_dep_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=16)),
                ('updated_at', models.DateField(auto_now=True)),
                ('npm_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages__app.npmpackage')),
            ],
        ),
    ]
