# Generated by Django 3.2.5 on 2021-08-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages__app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpmSecurityPackageDeatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_maintainers', models.IntegerField(default=1, null=True)),
                ('unpackedsize', models.IntegerField(null=True)),
                ('license', models.CharField(max_length=36)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_exploite', models.BooleanField()),
                ('num_high_severity', models.IntegerField(blank=True, default=0, null=True)),
                ('num_medium_severity', models.IntegerField(blank=True, default=0, null=True)),
                ('num_low_severity', models.IntegerField(blank=True, default=0, null=True)),
                ('npm_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages__app.npmpackage')),
            ],
        ),
    ]
