# Generated by Django 3.2.5 on 2021-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages__app', '0003_npmsecuritypackagedeatails_num_critical_severity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npmsecuritypackagedeatails',
            old_name='num_medium_severity',
            new_name='num_info_severity',
        ),
        migrations.AddField(
            model_name='npmsecuritypackagedeatails',
            name='num_moderate_severity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
