# Generated by Django 3.2.5 on 2021-09-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages__app', '0004_auto_20210831_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npmsecuritypackagedeatails',
            name='license',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
