# Generated by Django 3.2.5 on 2021-09-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages__app', '0005_alter_npmsecuritypackagedeatails_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpmProblemCallApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npm_package_name_problem', models.CharField(max_length=100)),
                ('version_problem', models.CharField(max_length=16)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
