# Generated by Django 3.2.5 on 2021-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages__app', '0008_alter_npmsecuritypackagedeatails_unpackedsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npmsecuritypackagedeatails',
            name='license',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
